# Generated by Django 5.0.2 on 2024-02-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deadline_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('tags', models.ManyToManyField(related_name='tasks', to='todo.tags')),
            ],
        ),
    ]
