# Generated by Django 5.0.2 on 2024-02-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_tags_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
